;;;;
;;;; ipautils.el: Utilities for working with the International Phonetic Alphabet
;;;; (IPA) in emacs.
;;;;
;;;; © Isaac Stead 2021
;;;;

(require 'cl-lib)
(require 'ido)

;;; Mnemonic IPA entry with autocompletion

(defconst ipautils-data
  ;; Derived from https://github.com/AdamSteffanick/ipa-data
  '(("p" . "voiceless bilabial plosive")
    ("b" . "voiced bilabial plosive")
    ("t" . "voiceless dental;alveolar plosive")
    ("d" . "voiced dental;alveolar plosive")
    ("ʈ" . "voiceless retroflex plosive")
    ("ɖ" . "voiced retroflex plosive")
    ("c" . "voiceless palatal plosive")
    ("ɟ" . "voiced palatal plosive")
    ("k" . "voiceless velar plosive")
    ("ɡ" . "voiced velar plosive")
    ("q" . "voiceless uvular plosive")
    ("ɢ" . "voiced uvular plosive")
    ("ʔ" . "glottal plosive")
    ("m" . "voiced bilabial nasal")
    ("ɱ" . "voiced labiodental nasal")
    ("n" . "voiced dental;alveolar nasal")
    ("ɳ" . "voiced retroflex nasal")
    ("ɲ" . "voiced palatal nasal")
    ("ŋ" . "voiced velar nasal")
    ("ɴ" . "voiced uvular nasal")
    ("ʙ" . "voiced bilabial trill")
    ("r" . "voiced dental;alveolar trill")
    ("ʀ" . "voiced uvular trill")
    ("ɾ" . "voiced dental;alveolar tap")
    ("ɽ" . "voiced retroflex flap")
    ("ɸ" . "voiceless bilabial fricative")
    ("β" . "voiced bilabial fricative")
    ("f" . "voiceless labiodental fricative")
    ("v" . "voiced labiodental fricative")
    ("θ" . "voiceless dental fricative")
    ("ð" . "voiced dental fricative")
    ("s" . "voiceless alveolar fricative")
    ("z" . "voiced alveolar fricative")
    ("ʃ" . "voiceless postalveolar fricative")
    ("ʒ" . "voiced postalveolar fricative")
    ("ʂ" . "voiceless retroflex fricative")
    ("ʐ" . "voiced retroflex fricative")
    ("ç" . "voiceless palatal fricative")
    ("ʝ" . "voiced palatal fricative")
    ("x" . "voiceless palatal fricative")
    ("ɣ" . "voiced velar fricative")
    ("χ" . "voiceless uvular fricative")
    ("ʁ" . "voiced uvular fricative")
    ("ħ" . "voiceless pharyngeal fricative")
    ("ʕ" . "voiced pharyngeal fricative;approximant")
    ("h" . "voiceless glottal fricative")
    ("ɦ" . "voiced glottal fricative")
    ("ɬ" . "voiceless dental;alveolar lateral fricative")
    ("ɮ" . "voiced dental;alveolar lateral fricative")
    ("ʋ" . "voiced labiodental approximant")
    ("ɹ" . "voiced dental;alveolar approximant")
    ("ɻ" . "voiced retroflex approximant")
    ("j" . "voiced palatal approximant")
    ("ɰ" . "voiced velar approximant")
    ("l" . "voiced dental;alveolar lateral approximant")
    ("ɭ" . "voiced retroflex lateral approximant")
    ("ʎ" . "voiced palatal lateral approximant")
    ("ʟ" . "voiced velar lateral approximant")
    ("ɓ" . "voiced bilabial implosive")
    ("ɗ" . "voiced dental;alveolar implosive")
    ("ʄ" . "voiced palatal implosive")
    ("ɠ" . "voiced velar implosive")
    ("ʛ" . "voiced uvular implosive")
    ("ʍ" . "voiceless labial-velar fricative")
    ("w" . "voiced labial-velar approximant")
    ("ɥ" . "voiced labial-palatal approximant")
    ("ʜ" . "voiceless epiglottal fricative")
    ("ʡ" . "epiglottal plosive")
    ("ʢ" . "voiced epiglottal fricative;approximant")
    ("ɧ" . "voiceless simultaneous postalveolar and velar fricative")
    ("ʘ" . "bilabial click")
    ("ǀ" . "dental click")
    ("ǃ" . "(post)alveolar click")
    ("ǂ" . "palatoalveolar click")
    ("ǁ" . "alveolar lateral click")
    ("ɺ" . "voiced alveolar lateral flap")
    ("ɕ" . "voiceless alveolo-palatal fricative")
    ("ʑ" . "voiced alveolo-palatal fricative")
    ("ⱱ" . "voiced labiodental flap")
    ("ɫ" . "velarized voiced dental;alveolar lateral approximant")
    ("ᶿ" . "voiceless dental fricative release")
    ("ᵊ" . "release mid central")
    ("ˣ" . "voiceless velar fricative release")
    ("i" . "close front unrounded")
    ("e" . "close-mid front unrounded")
    ("ɛ" . "open-mid front unrounded")
    ("a" . "open front unrounded")
    ("ɑ" . "open back unrounded")
    ("ɔ" . "open-mid back rounded")
    ("o" . "close-mid back rounded")
    ("u" . "close back rounded")
    ("y" . "close front rounded")
    ("ø" . "close-mid front rounded")
    ("œ" . "open-mid front rounded")
    ("ɶ" . "open front rounded")
    ("ɒ" . "open back rounded")
    ("ʌ" . "open-mid back unrounded")
    ("ɤ" . "close-mid back unrounded")
    ("ɯ" . "close back unrounded")
    ("ɨ" . "close central unrounded")
    ("ʉ" . "close central rounded")
    ("ɪ" . "near-close near-front unrounded")
    ("ʏ" . "near-close near-front rounded")
    ("ʊ" . "near-close near-back rounded")
    ("ə" . "mid central")
    ("ɵ" . "close-mid central rounded")
    ("ɐ" . "near-open central")
    ("æ" . "near-open front unrounded")
    ("ɜ" . "open-mid central unrounded")
    ("ɚ" . "R-coloured mid central")
    ("ɞ" . "open-mid central rounded")
    ("ɘ" . "close-mid central unrounded")
    ("ʼ" . "ejective")
    ("̬" . "voiced")
    ("ʰ" . "aspirated")
    ("̤" . "breathy voiced")
    ("̰" . "creaky voiced")
    ("̼" . "linguolabial")
    ("̪" . "dental")
    ("̺" . "apical")
    ("̻" . "laminal")
    ("̹" . "more rounded")
    ("̜" . "less rounded")
    ("̟" . "advanced")
    ("̠" . "retracted")
    ("̈" . "centralized")
    ("̽" . "mid-centralized")
    ("̘" . "advanced tongue root")
    ("̙" . "retracted tongue root")
    ("˞" . "rhoticity")
    ("ʷ" . "labialized")
    ("ʲ" . "palatalized")
    ("ˠ" . "velarized")
    ("ˤ" . "pharyngealized")
    ("̃" . "nasalized")
    ("ⁿ" . "nasal release")
    ("ˡ" . "lateral release")
    ("̚" . "no audible release")
    ("̴" . "velarized;pharyngealized")
    ("̝;˔" . "raising sign raised")
    ("̞;˕" . "lowering sign lowered")
    ("̩" . "syllabic")
    ("̯" . "non-syllabic")
    ("͡" . "affricate;double")
    ("˗" . "retracted variety (backed)")
    ("˖" . "advanced variety (fronted)")
    ("̣" . "closer variety;fricative")
    ("ˈ" . "primary stress")
    ("ˌ" . "secondary stress")
    ("ː" . "long")
    ("ˑ" . "half-long")
    ("̆" . "extra-short")
    ("." . "syllable break")
    ("|" . "minor (foot) group")
    ("‖" . "major (intonation) group")
    ("‿" . "linking (absence of a break)")
    ("↗" . "global rise")
    ("↘" . "global fall")
    ("̋" . "extra high level")
    ("́" . "high level")
    ("̄" . "mid level")
    ("̀" . "low level")
    ("̏" . "extra low level")
    ("↓" . "downstep")
    ("↑" . "upstep")
    ("˥" . "extra high level")
    ("˦" . "high level")
    ("˧" . "mid level")
    ("˨" . "low level")
    ("˩" . "extra low level")
    ("̌" . "rising contour")
    ("̂" . "falling contour")
    ("᷄" . "high rising contour")
    ("᷅" . "low rising contour")
    ("᷈" . "rising-falling contour")
    ("˩˥" . "rising contour")
    ("˥˩" . "falling contour")
    ("˦˥" . "high rising contour")
    ("˩˨" . "low rising contour")
    ("˧˦˧" . "rising-falling contour")
    ;; Later additions
    ("∅" . "null")
    ("⁄" . "slash") ; To be used for phoneme defs without interfering with org syntax
    ("ʷ" . "labialised")
    ("ᵐ" . "nasalised-bilabial")
    ("ᶮ" . "nasalised-palatal")
    ("ᵑ" . "nasalised-velar")))

(defconst ipautils-completions
  (cl-loop for pair in ipautils-data collect (cdr pair)))

;;;###autoload
(defun ipautils-insert ()
  (interactive)
  ;; Build list of completions within the function so it isn't prone to side effects
  (let ((completions (cl-loop for pair in ipautils-data collect (cdr pair))))
    (insert (car (rassoc (ido-completing-read "Features: "
                                              completions nil t)
                         ipautils-data)))))

;;;###autoload
(define-minor-mode ipautils-mode
  "Minor mode providing some small features to aid working with linguistics data"
  :lighter " lingmode"
  :keymap (let ((map (make-sparse-keymap)))
            (define-key map (kbd "C-c i") 'ipautils-insert)
            map))

(provide 'ipautils)
